/*
|-----------------------------------------
| setting up access-export.ts for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, 16 August 2026
|-----------------------------------------
*/

import type { AccessItem } from "@/redux/features/dashboard/types";

const encoder = new TextEncoder();
const encode = (value: string) => value.replace(/[<>&'\"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[char] ?? char);
export function downloadAccessZip(items: AccessItem[], kind: "export" | "bulk-export") { const rows = [["ID", "Email", "Role", "Status", "Created", "Updated"], ...items.map((item) => [item.id, item.email, item.roleName, item.blocked ? "Blocked" : "Active", item.createdAt ?? "", item.updatedAt ?? ""])]; const sheet = `<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((row, rowIndex) => `<row r="${rowIndex + 1}">${row.map((value, column) => `<c r="${String.fromCharCode(65 + column)}${rowIndex + 1}" t="inlineStr"><is><t>${encode(value)}</t></is></c>`).join("")}</row>`).join("")}</sheetData></worksheet>`; const xlsx = zip([["[Content_Types].xml", `<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`], ["_rels/.rels", `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`], ["xl/workbook.xml", `<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Access" sheetId="1" r:id="rId1"/></sheets></workbook>`], ["xl/_rels/workbook.xml.rels", `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`], ["xl/worksheets/sheet1.xml", sheet]]); const name = `${kind}-${new Date().toISOString().replace(/[:.]/g, "-")}`; const blob = new Blob([zip([[`${name}.xlsx`, xlsx]])], { type: "application/zip" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${name}.zip`; link.click(); URL.revokeObjectURL(link.href); }
function zip(files: [string, string | Uint8Array][]) { const local: Uint8Array[] = []; const central: Uint8Array[] = []; let offset = 0; for (const [name, source] of files) { const nameBytes = encoder.encode(name); const body = typeof source === "string" ? encoder.encode(source) : source; const crc = crc32(body); const item = new Uint8Array(30 + nameBytes.length + body.length); const view = new DataView(item.buffer); view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint32(14, crc, true); view.setUint32(18, body.length, true); view.setUint32(22, body.length, true); view.setUint16(26, nameBytes.length, true); item.set(nameBytes, 30); item.set(body, 30 + nameBytes.length); local.push(item); const entry = new Uint8Array(46 + nameBytes.length); const cv = new DataView(entry.buffer); cv.setUint32(0, 0x02014b50, true); cv.setUint16(4, 20, true); cv.setUint16(6, 20, true); cv.setUint32(16, crc, true); cv.setUint32(20, body.length, true); cv.setUint32(24, body.length, true); cv.setUint16(28, nameBytes.length, true); cv.setUint32(42, offset, true); entry.set(nameBytes, 46); central.push(entry); offset += item.length; } const size = central.reduce((sum, item) => sum + item.length, 0); const end = new Uint8Array(22); const ev = new DataView(end.buffer); ev.setUint32(0, 0x06054b50, true); ev.setUint16(8, files.length, true); ev.setUint16(10, files.length, true); ev.setUint32(12, size, true); ev.setUint32(16, offset, true); const parts = [...local, ...central, end]; const result = new Uint8Array(parts.reduce((sum, item) => sum + item.length, 0)); let at = 0; parts.forEach((item) => { result.set(item, at); at += item.length; }); return result; }
function crc32(data: Uint8Array) { let value = -1; for (const byte of data) { value ^= byte; for (let bit = 0; bit < 8; bit++) value = (value >>> 1) ^ (0xedb88320 & -(value & 1)); } return (value ^ -1) >>> 0; }
