/*
|-----------------------------------------
| setting up media-export.ts for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, 16 August 2026
|-----------------------------------------
*/

import type { MediaItem } from "@/redux/features/dashboard/types";

const encoder = new TextEncoder(); const xml = (value: string) => value.replace(/[<>&'\"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[char] ?? char);
/** Browser-only export: it uses already cached rows and makes no API request. */
export function downloadMediaZip(items: MediaItem[], kind: "export" | "bulk-export") { const rows = [["ID", "Name", "Author", "URL", "Provider", "Type", "Created at"], ...items.map((item) => [item.id, item.name, item.author, item.url, item.uploadPlane, item.type, new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.createdAt))])]; const sheet = `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((row, index) => `<row r="${index + 1}">${row.map((value, column) => `<c r="${String.fromCharCode(65 + column)}${index + 1}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`).join("")}</row>`).join("")}</sheetData></worksheet>`; const xlsx = zip([["[Content_Types].xml", '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'], ["_rels/.rels", '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'], ["xl/workbook.xml", '<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Media" sheetId="1" r:id="rId1"/></sheets></workbook>'], ["xl/_rels/workbook.xml.rels", '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'], ["xl/worksheets/sheet1.xml", sheet]]); const name = `media-${kind}-${new Date().toISOString().replace(/[:.]/g, "-")}`; const url = URL.createObjectURL(new Blob([zip([[`${name}.xlsx`, xlsx]])], { type: "application/zip" })); const link = document.createElement("a"); link.href = url; link.download = `${name}.zip`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }
function zip(files: [string, string | Uint8Array][]) { const local: Uint8Array[] = []; const central: Uint8Array[] = []; let offset = 0; for (const [name, source] of files) { const names = encoder.encode(name); const body = typeof source === "string" ? encoder.encode(source) : source; const checksum = crc32(body); const part = new Uint8Array(30 + names.length + body.length); const view = new DataView(part.buffer); view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint32(14, checksum, true); view.setUint32(18, body.length, true); view.setUint32(22, body.length, true); view.setUint16(26, names.length, true); part.set(names, 30); part.set(body, 30 + names.length); local.push(part); const entry = new Uint8Array(46 + names.length); const cv = new DataView(entry.buffer); cv.setUint32(0, 0x02014b50, true); cv.setUint16(4, 20, true); cv.setUint16(6, 20, true); cv.setUint32(16, checksum, true); cv.setUint32(20, body.length, true); cv.setUint32(24, body.length, true); cv.setUint16(28, names.length, true); cv.setUint32(42, offset, true); entry.set(names, 46); central.push(entry); offset += part.length; } const size = central.reduce((total, part) => total + part.length, 0); const end = new Uint8Array(22); const view = new DataView(end.buffer); view.setUint32(0, 0x06054b50, true); view.setUint16(8, files.length, true); view.setUint16(10, files.length, true); view.setUint32(12, size, true); view.setUint32(16, offset, true); const parts = [...local, ...central, end]; const result = new Uint8Array(parts.reduce((total, part) => total + part.length, 0)); let at = 0; for (const part of parts) { result.set(part, at); at += part.length; } return result; }
function crc32(data: Uint8Array) { let value = -1; for (const byte of data) { value ^= byte; for (let bit = 0; bit < 8; bit += 1) value = (value >>> 1) ^ (0xedb88320 & -(value & 1)); } return (value ^ -1) >>> 0; }
