/*
|-----------------------------------------
| setting up tracking-export.ts for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, 16 August, 2026
|-----------------------------------------
*/

import type { TrackingItem } from "@/redux/features/dashboard/tracking/trackingSlice";

const encoder = new TextEncoder();
const escapeXml = (value: string) => value.replace(/[<>&'\"]/g, (character) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[character] ?? character);
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

/** Creates the XLSX and its ZIP locally. It deliberately makes no API request. */
export function downloadTrackingZip(rows: TrackingItem[], prefix: "export" | "bulk-export") {
  const values = [["ID", "Provider", "Tracking ID", "Enabled", "Created at", "Updated at"], ...rows.map((item) => [item.id, item.provider, item.pixelId, item.enabled ? "Enabled" : "Disabled", formatDate(item.createdAt), formatDate(item.updatedAt)])];
  const sheet = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${values.map((row, rowIndex) => `<row r="${rowIndex + 1}">${row.map((value, column) => `<c r="${String.fromCharCode(65 + column)}${rowIndex + 1}" t="inlineStr"><is><t>${escapeXml(value)}</t></is></c>`).join("")}</row>`).join("")}</sheetData></worksheet>`;
  const xlsx = zip([["[Content_Types].xml", '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'], ["_rels/.rels", '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'], ["xl/workbook.xml", '<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Tracking" sheetId="1" r:id="rId1"/></sheets></workbook>'], ["xl/_rels/workbook.xml.rels", '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'], ["xl/worksheets/sheet1.xml", sheet]]);
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-"); const filename = `tracking-${prefix}-${timestamp}`;
  const url = URL.createObjectURL(new Blob([zip([[`${filename}.xlsx`, xlsx]])], { type: "application/zip" })); const link = document.createElement("a"); link.href = url; link.download = `${filename}.zip`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 0);
}
function zip(files: [string, string | Uint8Array][]) { const locals: Uint8Array[] = []; const directory: Uint8Array[] = []; let offset = 0; for (const [name, source] of files) { const nameBytes = encoder.encode(name); const body = typeof source === "string" ? encoder.encode(source) : source; const checksum = crc32(body); const local = new Uint8Array(30 + nameBytes.length + body.length); const view = new DataView(local.buffer); view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint32(14, checksum, true); view.setUint32(18, body.length, true); view.setUint32(22, body.length, true); view.setUint16(26, nameBytes.length, true); local.set(nameBytes, 30); local.set(body, 30 + nameBytes.length); locals.push(local); const record = new Uint8Array(46 + nameBytes.length); const recordView = new DataView(record.buffer); recordView.setUint32(0, 0x02014b50, true); recordView.setUint16(4, 20, true); recordView.setUint16(6, 20, true); recordView.setUint32(16, checksum, true); recordView.setUint32(20, body.length, true); recordView.setUint32(24, body.length, true); recordView.setUint16(28, nameBytes.length, true); recordView.setUint32(42, offset, true); record.set(nameBytes, 46); directory.push(record); offset += local.length; } const size = directory.reduce((total, entry) => total + entry.length, 0); const end = new Uint8Array(22); const endView = new DataView(end.buffer); endView.setUint32(0, 0x06054b50, true); endView.setUint16(8, files.length, true); endView.setUint16(10, files.length, true); endView.setUint32(12, size, true); endView.setUint32(16, offset, true); const parts = [...locals, ...directory, end]; const result = new Uint8Array(parts.reduce((total, part) => total + part.length, 0)); let index = 0; for (const part of parts) { result.set(part, index); index += part.length; } return result; }
function crc32(bytes: Uint8Array) { let value = -1; for (const byte of bytes) { value ^= byte; for (let bit = 0; bit < 8; bit += 1) value = (value >>> 1) ^ (0xedb88320 & -(value & 1)); } return (value ^ -1) >>> 0; }
