/*
|-----------------------------------------
| setting up verification-export.ts for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, 16 August 2026
|-----------------------------------------
*/

import type { VerificationItem } from "@/redux/features/dashboard/verifications/verificationsSlice";

const text = new TextEncoder();
const date = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const xml = (value: string) => value.replace(/[<>&'\"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[c] ?? c);

/** Generates entirely in the browser: no export API or server data request is made. */
export function downloadVerificationZip(rows: VerificationItem[], prefix: "export" | "bulk-export") {
  const values = [["ID", "Type", "Identifier", "Created at", "Expires at", "Updated at"], ...rows.map((item) => [item.id, item.type, item.identifier, date(item.createdAt), date(item.expiresAt), date(item.updatedAt)])];
  const sheet = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${values.map((row, rowIndex) => `<row r="${rowIndex + 1}">${row.map((value, column) => `<c r="${String.fromCharCode(65 + column)}${rowIndex + 1}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`).join("")}</row>`).join("")}</sheetData></worksheet>`;
  const xlsx = zip([["[Content_Types].xml", `<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`], ["_rels/.rels", `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`], ["xl/workbook.xml", `<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Verifications" sheetId="1" r:id="rId1"/></sheets></workbook>`], ["xl/_rels/workbook.xml.rels", `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`], ["xl/worksheets/sheet1.xml", sheet]]);
  const name = `${prefix}-${new Date().toISOString().replace(/[:.]/g, "-")}`; const blob = new Blob([zip([[`${name}.xlsx`, xlsx]])], { type: "application/zip" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${name}.zip`; link.click(); URL.revokeObjectURL(link.href);
}
function zip(files: [string, string | Uint8Array][]) { const locals: Uint8Array[] = []; const directory: Uint8Array[] = []; let offset = 0; for (const [name, source] of files) { const n = text.encode(name); const body = typeof source === "string" ? text.encode(source) : source; const crc = crc32(body); const local = new Uint8Array(30 + n.length + body.length); const view = new DataView(local.buffer); view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint32(14, crc, true); view.setUint32(18, body.length, true); view.setUint32(22, body.length, true); view.setUint16(26, n.length, true); local.set(n, 30); local.set(body, 30 + n.length); locals.push(local); const record = new Uint8Array(46 + n.length); const rv = new DataView(record.buffer); rv.setUint32(0, 0x02014b50, true); rv.setUint16(4, 20, true); rv.setUint16(6, 20, true); rv.setUint32(16, crc, true); rv.setUint32(20, body.length, true); rv.setUint32(24, body.length, true); rv.setUint16(28, n.length, true); rv.setUint32(42, offset, true); record.set(n, 46); directory.push(record); offset += local.length; } const directorySize = directory.reduce((sum, item) => sum + item.length, 0); const end = new Uint8Array(22); const ev = new DataView(end.buffer); ev.setUint32(0, 0x06054b50, true); ev.setUint16(8, files.length, true); ev.setUint16(10, files.length, true); ev.setUint32(12, directorySize, true); ev.setUint32(16, offset, true); const pieces = [...locals, ...directory, end]; const result = new Uint8Array(pieces.reduce((sum, item) => sum + item.length, 0)); let at = 0; for (const piece of pieces) { result.set(piece, at); at += piece.length; } return result; }
function crc32(bytes: Uint8Array) { let value = -1; for (const byte of bytes) { value ^= byte; for (let bit = 0; bit < 8; bit++) value = (value >>> 1) ^ (0xedb88320 & -(value & 1)); } return (value ^ -1) >>> 0; }
