/*
|-----------------------------------------
| setting up data.ts for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, 16 August 2026
|-----------------------------------------
*/

import type { MenuData } from "../menu-1/data";

export const defaultData: MenuData = {
  variant: "menu-3",
  isVisible: true,
  brand: "TecBuzz",
  logoUrl: "/Logo.png",
  logoAlt: "TecBuzz logo",
  showLogo: true,
  showBrand: true,
  brandColor: "#0b1736",
  brandFontFamily: "inherit",
  brandFontSize: 16,
  logoPositionX: 0,
  logoPositionY: 0,
  logoDesktopPaddingX: 0,
  logoDesktopPaddingY: 0,
  logoDesktopMarginX: 0,
  logoDesktopMarginY: 0,
  logoMobilePaddingX: 0,
  logoMobilePaddingY: 0,
  logoMobileMarginX: 0,
  logoMobileMarginY: 0,
  logoAspect: "full",
  links: [
    { id: "home", label: "Home", url: "/", visible: true, position: 0 },
    {
      id: "services",
      label: "Services",
      url: "/services",
      visible: true,
      position: 1,
      children: [
        {
          id: "website-development",
          label: "Website Development",
          url: "/website-development",
          visible: true,
          position: 0,
        },
        {
          id: "business-automation",
          label: "Business Automation",
          url: "/business-automation",
          visible: true,
          position: 1,
        },
        {
          id: "content-social-media",
          label: "Content and Social",
          url: "/content-social-media",
          visible: true,
          position: 2,
        },
        { id: "seo", label: "SEO Service", url: "/seo", visible: true, position: 3 },
        { id: "ads-management", label: "Ads Management", url: "/ads-management", visible: true, position: 4 },
      ],
    },
    {
      id: "solutions",
      label: "Solutions",
      url: "/solutions",
      visible: true,
      position: 2,
      children: [
        {
          id: "education-coaching",
          label: "Education and Coaching",
          url: "/solutions/education-coaching",
          visible: true,
          position: 0,
        },
        {
          id: "clinic-healthcare",
          label: "Clinic and Healthcare",
          url: "/solutions/clinic-healthcare",
          visible: true,
          position: 1,
        },
        {
          id: "sme-corporate",
          label: "SME and Corporate",
          url: "/solutions/sme-corporate",
          visible: true,
          position: 2,
        },
        { id: "ecommerce", label: "E-commerce", url: "/solutions/ecommerce", visible: true, position: 3 },
        {
          id: "professional-services",
          label: "Professional Services",
          url: "/solutions/professional-services",
          visible: true,
          position: 4,
        },
      ],
    },
    { id: "portfolio", label: "Portfolio", url: "/portfolio", visible: true, position: 3 },
    { id: "pricing", label: "Pricing", url: "/pricing", visible: true, position: 4 },
    {
      id: "resources",
      label: "Resources",
      url: "/blog",
      visible: true,
      position: 5,
      children: [
        { id: "blog", label: "Blog", url: "/blog", visible: true, position: 0 },
        { id: "static-posts", label: "Static Post Examples", url: "/static-posts", visible: true, position: 1 },
        { id: "reels", label: "Reels Examples", url: "/reels", visible: true, position: 2 },
        { id: "ad-creatives", label: "Ad Creative Gallery", url: "/ad-creatives", visible: true, position: 3 },
        { id: "faq", label: "FAQ", url: "/frequently-ask-questions", visible: true, position: 4 },
      ],
    },
    { id: "about", label: "About", url: "/about", visible: true, position: 6 },
  ],
  background: "#ffffff",
  foreground: "#0b1736",
  accent: "#087af5",
  position: "sticky",
  transparency: 100,
  fontSize: 14,
  fontFamily: "inherit",
  button: {
    type: "custom",
    label: "Free Audit",
    url: "/free-audit",
    icon: "ArrowRight",
    showIcon: true,
    background: "#087af5",
    foreground: "#ffffff",
    transparency: 100,
    paddingX: 14,
    paddingY: 8,
    mobilePaddingX: 14,
    mobilePaddingY: 8,
    mobileMarginX: 0,
    mobileMarginY: 0,
    desktopPaddingX: 14,
    desktopPaddingY: 8,
    desktopMarginX: 0,
    desktopMarginY: 0,
    border: "xs",
    radius: "sm",
  },
  mobile: { enabled: false, layout: "grid-2-2", links: [] },
  // menu-3-specific values demonstrate the mixed JSON contract.
  layout: { container: "wide", linkStyle: "pill" },
};
