/*
|-----------------------------------------
| setting up data.ts for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, 16 August 2026
|-----------------------------------------
*/

import type { MenuData, MenuLink } from "../menu-1/data";

export type MenuThreeLink = MenuLink & {
  description?: string;
  price?: string;
  originalPrice?: string;
  saving?: string;
  inclusions?: string[];
  note?: string;
  children?: MenuThreeLink[];
};

const whatsappUrl = "https://wa.me/8801607333369";
const enquireAbout = (service: string) => `${whatsappUrl}?text=${encodeURIComponent(`${service} সম্পর্কে জানতে চাই।`)}`;

export const defaultData: MenuData & { links: MenuThreeLink[] } = {
  variant: "menu-3",
  isVisible: true,
  brand: "TecBuzz",
  logoUrl: "/Logo.png",
  logoAlt: "TecBuzz logo",
  showLogo: true,
  showBrand: true,
  brandColor: "#0b1736",
  brandFontFamily: "inherit",
  brandFontSize: 16,
  logoPositionX: 0,
  logoPositionY: 0,
  logoDesktopPaddingX: 0,
  logoDesktopPaddingY: 0,
  logoDesktopMarginX: 0,
  logoDesktopMarginY: 0,
  logoMobilePaddingX: 0,
  logoMobilePaddingY: 0,
  logoMobileMarginX: 0,
  logoMobileMarginY: 0,
  logoAspect: "full",
  links: [
    { id: "home", label: "হোম", url: "/", visible: true, position: 0 },
    {
      id: "packages",
      label: "প্যাকেজ",
      url: "/#pricing",
      visible: true,
      position: 1,
      note: "Standard Express build: অগ্রিম অর্থ, প্রয়োজনীয় assets ও scope approval-এর পর ২৪–৪৮ ঘণ্টায় দেওয়া সম্ভব।",
      children: [
        {
          id: "tecbuzz-starter",
          label: "TecBuzz Starter",
          url: enquireAbout("TecBuzz Starter — ৳14,900"),
          price: "৳14,900",
          inclusions: ["Website", "SEO"],
          icon: "Globe",
          showIcon: true,
          visible: true,
          position: 0,
        },
        {
          id: "lead-express",
          label: "Lead Express",
          url: enquireAbout("Lead Express — ৳24,900"),
          price: "৳24,900",
          inclusions: ["Website + SEO", "১ মাসের কনটেন্ট", "Marketing Support"],
          icon: "Zap",
          showIcon: true,
          visible: true,
          position: 1,
        },
        {
          id: "enterprise",
          label: "Enterprise",
          url: enquireAbout("Enterprise — ৳79,900"),
          price: "৳79,900",
          inclusions: ["Website + SEO", "১ মাসে ব্যবসার প্রয়োজন অনুযায়ী আপডেট", "Marketing Support", "২ মাসের কনটেন্ট"],
          icon: "Settings",
          showIcon: true,
          visible: true,
          position: 2,
        },
      ],
    },
    {
      id: "content",
      label: "কনটেন্ট",
      url: enquireAbout("মাসিক কনটেন্ট প্ল্যান"),
      visible: true,
      position: 2,
      note: "মাসিক কনটেন্ট প্ল্যান অথবা প্রয়োজন অনুযায়ী Reels, Static Posts ও Ad Creatives বেছে নিন।",
      children: [
        {
          id: "content-lite",
          label: "Content Lite",
          url: enquireAbout("Content Lite — ৳5,000/মাস"),
          originalPrice: "৳7,650/মাস",
          price: "৳5,000/মাস",
          saving: "৳2,650 সাশ্রয় · প্রায় 35% ছাড়",
          inclusions: ["12 Reels", "30 Static Posts", "21 Ad Creatives"],
          icon: "Video",
          showIcon: true,
          visible: true,
          position: 0,
        },
        {
          id: "content-growth",
          label: "Content Growth",
          url: enquireAbout("Content Growth — ৳7,500/মাস"),
          originalPrice: "৳12,150/মাস",
          price: "৳7,500/মাস",
          saving: "৳4,650 সাশ্রয় · প্রায় 38% ছাড়",
          inclusions: ["30 Reels", "30 Static Posts", "21 Ad Creatives"],
          icon: "BarChart",
          showIcon: true,
          visible: true,
          position: 1,
        },
        {
          id: "content-scale",
          label: "Content Scale",
          url: enquireAbout("Content Scale — ৳13,500/মাস"),
          originalPrice: "৳24,300/মাস",
          price: "৳13,500/মাস",
          saving: "৳10,800 সাশ্রয় · প্রায় 44% ছাড়",
          inclusions: ["60 Reels", "60 Static Posts", "42 Ad Creatives"],
          icon: "Zap",
          showIcon: true,
          visible: true,
          position: 2,
        },
        {
          id: "single-reel",
          label: "Reels",
          url: enquireAbout("Reels — প্রতিটি ৳250"),
          price: "৳250 / প্রতিটি",
          icon: "Video",
          showIcon: true,
          visible: true,
          position: 3,
        },
        {
          id: "single-static",
          label: "Static Posts",
          url: enquireAbout("Static Posts — প্রতিটি ৳50"),
          price: "৳50 / প্রতিটি",
          icon: "Image",
          showIcon: true,
          visible: true,
          position: 4,
        },
        {
          id: "single-ad-creative",
          label: "Ad Creatives",
          url: enquireAbout("Ad Creatives — প্রতিটি ৳150"),
          price: "৳150 / প্রতিটি",
          icon: "Target",
          showIcon: true,
          visible: true,
          position: 5,
        },
      ],
    },
    {
      id: "website-features",
      label: "ওয়েবসাইট ফিচার",
      url: enquireAbout("TecBuzz Website Features"),
      visible: true,
      position: 3,
      children: [
        {
          id: "fast-loading",
          label: "দ্রুত লোডিং",
          description: "সব ডিভাইসে দ্রুত লোডিংয়ের জন্য অপ্টিমাইজ করা ওয়েবসাইট।",
          url: enquireAbout("Fast Loading Performance"),
          icon: "Zap",
          showIcon: true,
          visible: true,
          position: 0,
        },
        {
          id: "unlimited-pages",
          label: "আনলিমিটেড পেজ",
          description: "ব্যবসার প্রয়োজন অনুযায়ী সীমাহীন পেজ তৈরি করুন।",
          url: enquireAbout("Unlimited Page Creation"),
          icon: "FileText",
          showIcon: true,
          visible: true,
          position: 1,
        },
        {
          id: "vercel-hosting",
          label: "Vercel Cloud Hosting",
          description:
            "SSL, Global CDN ও automatic deployment। Free Tier testing/personal projects-এর জন্য; business website-এর জন্য প্রয়োজন অনুযায়ী premium hosting।",
          url: enquireAbout("Vercel Cloud Hosting"),
          icon: "Cloud",
          showIcon: true,
          visible: true,
          position: 2,
        },
        {
          id: "secure-access",
          label: "নিরাপদ Auth ও Authorization",
          description: "রোলভিত্তিক লগইন ও অনুমোদিত ডেটায় প্রবেশাধিকার।",
          url: enquireAbout("Secure Auth & Authorization"),
          icon: "ShieldCheck",
          showIcon: true,
          visible: true,
          position: 3,
        },
        {
          id: "employee-management",
          label: "Employee Management",
          description: "কর্মী যোগ, আপডেট ও তাদের কার্যক্রম পর্যবেক্ষণ।",
          url: enquireAbout("Employee Management System"),
          icon: "Users",
          showIcon: true,
          visible: true,
          position: 4,
        },
        {
          id: "pwa",
          label: "Progressive Web App",
          description: "মোবাইল ও ডেস্কটপে ইনস্টলযোগ্য, সীমিত ইন্টারনেটেও ব্যবহারযোগ্য অভিজ্ঞতা।",
          url: enquireAbout("Progressive Web App — PWA"),
          icon: "Globe",
          showIcon: true,
          visible: true,
          position: 5,
        },
        {
          id: "user-blocking",
          label: "User Blocking",
          description: "অ্যাডমিনের মাধ্যমে ব্যবহারকারী ব্লক বা সীমাবদ্ধ করুন।",
          url: enquireAbout("User Blocking System"),
          icon: "Lock",
          showIcon: true,
          visible: true,
          position: 6,
        },
        {
          id: "analytics",
          label: "Google Tag ও Facebook Pixel",
          description: "Google Tag Manager ও Facebook Pixel দিয়ে ব্যবহারকারীর আচরণ ও মার্কেটিং পারফরম্যান্স দেখুন।",
          url: enquireAbout("Google Tag & Facebook Pixel"),
          icon: "BarChart",
          showIcon: true,
          visible: true,
          position: 7,
        },
        {
          id: "seo",
          label: "SEO Optimization",
          description: "সার্চ ইঞ্জিনে ভিজিবিলিটির জন্য প্রয়োজনীয় প্রস্তুতি।",
          url: enquireAbout("SEO Optimization"),
          icon: "Search",
          showIcon: true,
          visible: true,
          position: 8,
        },
        {
          id: "facebook-setup",
          label: "Facebook Page Setup",
          description: "পেজ তৈরি ও অপ্টিমাইজেশন, প্রথম সপ্তাহের রেডি-টু-ইউজ কনটেন্টসহ।",
          url: enquireAbout("Facebook Page Setup"),
          icon: "CiFacebook",
          showIcon: true,
          visible: true,
          position: 9,
        },
        {
          id: "ad-support",
          label: "Ad Boosting Support",
          description: "সঠিক দর্শকদের কাছে পৌঁছাতে পেইড অ্যাড পরিচালনা ও অপ্টিমাইজেশনে সহায়তা।",
          url: enquireAbout("Ad Boosting Support"),
          icon: "BarChart",
          showIcon: true,
          visible: true,
          position: 10,
        },
      ],
    },
    { id: "portfolio", label: "আমাদের কাজ", url: "/#demos", visible: true, position: 4 },
    { id: "pricing", label: "প্রাইসিং", url: "/#pricing", visible: true, position: 5 },
  ],
  background: "#ffffff",
  foreground: "#0b1736",
  accent: "#087af5",
  position: "sticky",
  transparency: 100,
  fontSize: 14,
  fontFamily: "inherit",
  button: {
    type: "custom",
    label: "WhatsApp",
    url: whatsappUrl,
    icon: "FaWhatsapp",
    showIcon: true,
    background: "#087af5",
    foreground: "#ffffff",
    transparency: 100,
    paddingX: 14,
    paddingY: 8,
    mobilePaddingX: 14,
    mobilePaddingY: 8,
    mobileMarginX: 0,
    mobileMarginY: 0,
    desktopPaddingX: 14,
    desktopPaddingY: 8,
    desktopMarginX: 0,
    desktopMarginY: 0,
    border: "xs",
    radius: "sm",
  },
  mobile: { enabled: false, layout: "grid-2-2", links: [] },
  layout: { container: "wide", linkStyle: "pill" },
};
